/*
 * guest/kernel.c - main execution loop of the bare-metal C64 guest.
 *
 * Initializes every emulated chip, single-steps the 6502 CPU core
 * (fake6502), times VIC-II/CIA/SID off the CPU cycles actually consumed,
 * dispatches IRQ/NMI interrupts, reads the keyboard (host port 0x60),
 * intercepts KERNAL LOAD/SAVE for the instant .PRG/.D64 fast-loader
 * (ports 0x5007/0x5008), streams SID audio to the host (port 0x5006),
 * drives the SID hypercall player loader ($F700, see do_sid_load()), and
 * writes diagnostic output to the host console (port 0x5001).
 *
 * Part of v-c64 - a bare-metal Commodore 64 unikernel running directly
 * on Linux /dev/kvm, with no QEMU involved.
 *
 * Author: Dariusz Nowak <hal.dariusz.nowak@gmail.com>
 */
#include "kernel.h"
#include "fake6502.h"
#include "memory_pla.h"
#include "c64bus.h"
#include "vic2.h"
#include "cia.h"
#include "sid.h"
#include "reu.h"
#include "cartridge.h"
#include "libc_shim.h"
#include <stdint.h>
#include <stdbool.h>

/* ROMs generated by the Makefile rule: xxd -i -n <name>_file, roms directory */
#include "rom_kernal.h"
#include "rom_basic.h"
#include "rom_chargen.h"
#include "rom_simons.h"

/* --- minimal libc (freestanding: no libc to link against) ----------------- */

void *memset(void *dst, int val, unsigned int n)
{
    uint8_t *p = (uint8_t *)dst;
    for (unsigned int i = 0; i < n; i++) p[i] = (uint8_t)val;
    return dst;
}

void *memcpy(void *dst, const void *src, unsigned int n)
{
    uint8_t *d = (uint8_t *)dst;
    const uint8_t *s = (const uint8_t *)src;
    for (unsigned int i = 0; i < n; i++) d[i] = s[i];
    return dst;
}

/* --- host<->guest hypervisor protocol I/O ports (see host/kvm_host.c) ---- */

#define PORT_KEYBOARD       0x60   /* IN byte: next x86 scancode (0 = none) */
#define PORT_DEBUG_CONSOLE  0x5001 /* OUT byte: diagnostic log on the host terminal */
#define PORT_AUDIO_SAMPLE   0x5006 /* OUT word: SID sample (16-bit signed) */
#define PORT_FASTLOAD_CMD   0x5007 /* OUT: 1=filename starts,2=filename complete; IN: status/length/address */
#define PORT_FASTLOAD_DATA  0x5008 /* OUT: next filename byte; IN: next data byte */

static inline void outb(uint16_t port, uint8_t val) { asm volatile("outb %0,%1" :: "a"(val), "Nd"(port)); }
static inline void outw(uint16_t port, uint16_t val) { asm volatile("outw %0,%1" :: "a"(val), "Nd"(port)); }
static inline uint8_t inb(uint16_t port) { uint8_t r; asm volatile("inb %1,%0" : "=a"(r) : "Nd"(port)); return r; }

static void debug_puts(const char *s)
{
    while (*s) outb(PORT_DEBUG_CONSOLE, (uint8_t)*s++);
}

static void debug_puthex16(uint16_t v)
{
    static const char hex[] = "0123456789ABCDEF";
    char buf[5];
    for (int i = 3; i >= 0; i--) { buf[i] = hex[v & 0xF]; v >>= 4; }
    buf[4] = 0;
    debug_puts(buf);
}

/* --- fast-loader: intercepting the KERNAL LOAD routine ($F4A5) ------------ */

static void do_fast_load(fake6502_context *cpu)
{
    uint8_t fnlen = c64_ram[0xB7];
    uint16_t fnaddr = (uint16_t)(c64_ram[0xBB] | (c64_ram[0xBC] << 8));

    outb(PORT_FASTLOAD_CMD, 0x01); /* start filename transmission */
    for (uint8_t i = 0; i < fnlen; i++)
        outb(PORT_FASTLOAD_DATA, fake6502_mem_read(cpu, (uint16_t)(fnaddr + i)));
    outb(PORT_FASTLOAD_CMD, 0x02); /* filename complete - host performs the load */

    uint8_t status = inb(PORT_FASTLOAD_CMD);
    uint16_t ret_addr = fake6502_pull_16(cpu); /* simulates an RTS from JSR $FFD5 */

    if (!status) {
        debug_puts("LOAD: file not found\n");
        fake6502_carry_set(cpu);
        cpu->cpu.pc = (uint16_t)(ret_addr + 1);
        return;
    }

    uint16_t length = (uint16_t)(inb(PORT_FASTLOAD_DATA) | (inb(PORT_FASTLOAD_DATA) << 8));
    uint16_t load_addr = (uint16_t)(inb(PORT_FASTLOAD_DATA) | (inb(PORT_FASTLOAD_DATA) << 8));

    /* Destination address always taken from the .prg file header (works
     * correctly for the vast majority of real-world use cases -
     * LOAD"name",8 - without trying to reproduce the nuances of the
     * secondary address $B9=1 relative to a loosely-defined zero-page
     * pointer). */
    uint16_t dest = load_addr;

    for (uint16_t i = 0; i < length; i++)
        c64_ram[(uint16_t)(dest + i)] = inb(PORT_FASTLOAD_DATA);

    uint16_t end_addr = (uint16_t)(dest + length);
    cpu->cpu.x = (uint8_t)(end_addr & 0xFF);
    cpu->cpu.y = (uint8_t)(end_addr >> 8);
    fake6502_carry_clear(cpu);
    cpu->cpu.pc = (uint16_t)(ret_addr + 1);

    /* VARTAB ($2D/$2E): just like the real KERNAL, we move the start of
     * the BASIC variable table to right after the loaded program. */
    c64_ram[0x2D] = (uint8_t)(end_addr & 0xFF);
    c64_ram[0x2E] = (uint8_t)(end_addr >> 8);

    debug_puts("LOAD: OK, end=$");
    debug_puthex16(end_addr);
    debug_puts("\n");
}

/* --- fast-saver: intercepting the KERNAL SAVE routine ($F5DD) ------------- */

static void do_fast_save(fake6502_context *cpu)
{
    uint8_t fnlen = c64_ram[0xB7];
    uint16_t fnaddr = (uint16_t)(c64_ram[0xBB] | (c64_ram[0xBC] << 8));

    /* KERNAL SAVE calling convention: A = zero-page address pointing to
     * the 2-byte start address of the data, X/Y = end address. */
    uint8_t zp_ptr = cpu->cpu.a;
    uint16_t start_addr = (uint16_t)(c64_ram[zp_ptr] | (c64_ram[(uint8_t)(zp_ptr + 1)] << 8));
    uint16_t end_addr = (uint16_t)(cpu->cpu.x | (cpu->cpu.y << 8));
    uint16_t length = (uint16_t)(end_addr - start_addr);

    outb(PORT_FASTLOAD_CMD, 0x03); /* start filename transmission (SAVE) */
    for (uint8_t i = 0; i < fnlen; i++)
        outb(PORT_FASTLOAD_DATA, fake6502_mem_read(cpu, (uint16_t)(fnaddr + i)));
    outb(PORT_FASTLOAD_CMD, 0x04); /* filename complete - now header + data */
    outb(PORT_FASTLOAD_DATA, (uint8_t)(start_addr & 0xFF));
    outb(PORT_FASTLOAD_DATA, (uint8_t)(start_addr >> 8));
    outb(PORT_FASTLOAD_DATA, (uint8_t)(length & 0xFF));
    outb(PORT_FASTLOAD_DATA, (uint8_t)(length >> 8));
    for (uint16_t i = 0; i < length; i++)
        outb(PORT_FASTLOAD_DATA, c64_ram[(uint16_t)(start_addr + i)]);
    outb(PORT_FASTLOAD_CMD, 0x05); /* perform the write on the host */

    uint8_t status = inb(PORT_FASTLOAD_CMD);
    uint16_t ret_addr = fake6502_pull_16(cpu);
    if (status) fake6502_carry_clear(cpu); else fake6502_carry_set(cpu);
    cpu->cpu.pc = (uint16_t)(ret_addr + 1);

    debug_puts(status ? "SAVE: OK\n" : "SAVE: error\n");
}

/* --- SID-load: a custom "hypercall" (PC == $F700, not a real KERNAL
 * routine) for loading PSID/RSID files. The host parses the header and
 * returns ready-made load/init/play addresses plus the song count, which
 * we load into a zero-page "mailbox" ($02-$0A) for the guest program's
 * use (see tools/sidplayer). Uses the same filename convention as LOAD
 * ($B7/$BB/$BC), so the guest program can set it up identically to LOAD. */
#define SID_MB_LOAD   0x02  /* +0/+1: data load address */
#define SID_MB_INIT   0x04  /* +0/+1: init routine address */
#define SID_MB_PLAY   0x06  /* +0/+1: play routine address (0 = tune installs its own IRQ) */
#define SID_MB_SONGS  0x08  /* number of subsongs */
#define SID_MB_START  0x09  /* default subsong, already 0-based (to write into A at init) */
#define SID_MB_STATUS 0x0A  /* 1 = OK, 0 = error/not found */

static void do_sid_load(fake6502_context *cpu)
{
    uint8_t fnlen = c64_ram[0xB7];
    uint16_t fnaddr = (uint16_t)(c64_ram[0xBB] | (c64_ram[0xBC] << 8));

    outb(PORT_FASTLOAD_CMD, 0x06); /* SIDLOAD: start filename */
    for (uint8_t i = 0; i < fnlen; i++)
        outb(PORT_FASTLOAD_DATA, fake6502_mem_read(cpu, (uint16_t)(fnaddr + i)));
    outb(PORT_FASTLOAD_CMD, 0x07); /* SIDLOAD: execute */

    uint8_t status = inb(PORT_FASTLOAD_CMD);
    c64_ram[SID_MB_STATUS] = status;

    if (status) {
        uint16_t load_addr = (uint16_t)(inb(PORT_FASTLOAD_DATA) | (inb(PORT_FASTLOAD_DATA) << 8));
        uint16_t init_addr = (uint16_t)(inb(PORT_FASTLOAD_DATA) | (inb(PORT_FASTLOAD_DATA) << 8));
        uint16_t play_addr = (uint16_t)(inb(PORT_FASTLOAD_DATA) | (inb(PORT_FASTLOAD_DATA) << 8));
        uint8_t songs = inb(PORT_FASTLOAD_DATA);
        uint8_t start_song = inb(PORT_FASTLOAD_DATA);
        uint16_t length = (uint16_t)(inb(PORT_FASTLOAD_DATA) | (inb(PORT_FASTLOAD_DATA) << 8));

        for (uint16_t i = 0; i < length; i++)
            c64_ram[(uint16_t)(load_addr + i)] = inb(PORT_FASTLOAD_DATA);

        c64_ram[SID_MB_LOAD]     = (uint8_t)(load_addr & 0xFF);
        c64_ram[SID_MB_LOAD + 1] = (uint8_t)(load_addr >> 8);
        c64_ram[SID_MB_INIT]     = (uint8_t)(init_addr & 0xFF);
        c64_ram[SID_MB_INIT + 1] = (uint8_t)(init_addr >> 8);
        c64_ram[SID_MB_PLAY]     = (uint8_t)(play_addr & 0xFF);
        c64_ram[SID_MB_PLAY + 1] = (uint8_t)(play_addr >> 8);
        c64_ram[SID_MB_SONGS]    = songs;
        c64_ram[SID_MB_START]    = start_song;

        debug_puts("SIDLOAD: OK, init=$");
        debug_puthex16(init_addr);
        debug_puts(" play=$");
        debug_puthex16(play_addr);
        debug_puts("\n");
    } else {
        debug_puts("SIDLOAD: error\n");
    }

    uint16_t ret_addr = fake6502_pull_16(cpu);
    if (status) fake6502_carry_clear(cpu); else fake6502_carry_set(cpu);
    cpu->cpu.pc = (uint16_t)(ret_addr + 1);
}

/* --- keyboard: x86 scancodes (Set 1) -> 8x8 C64 matrix -------------------- */

typedef struct { uint8_t row, col; } key_map_t;
#define KM_NONE ((key_map_t){0xFF, 0xFF})

static key_map_t scancode_to_c64(uint8_t sc)
{
    switch (sc) {
        case 0x1E: return (key_map_t){1, 2}; /* A */
        case 0x30: return (key_map_t){3, 4}; /* B */
        case 0x2E: return (key_map_t){2, 4}; /* C */
        case 0x20: return (key_map_t){2, 2}; /* D */
        case 0x12: return (key_map_t){1, 6}; /* E */
        case 0x21: return (key_map_t){2, 5}; /* F */
        case 0x22: return (key_map_t){3, 2}; /* G */
        case 0x23: return (key_map_t){3, 5}; /* H */
        case 0x17: return (key_map_t){4, 1}; /* I */
        case 0x24: return (key_map_t){4, 2}; /* J */
        case 0x25: return (key_map_t){4, 5}; /* K */
        case 0x26: return (key_map_t){5, 2}; /* L */
        case 0x32: return (key_map_t){4, 4}; /* M */
        case 0x31: return (key_map_t){4, 7}; /* N */
        case 0x18: return (key_map_t){4, 6}; /* O */
        case 0x19: return (key_map_t){5, 1}; /* P */
        case 0x10: return (key_map_t){7, 6}; /* Q */
        case 0x13: return (key_map_t){2, 1}; /* R */
        case 0x1F: return (key_map_t){1, 5}; /* S */
        case 0x14: return (key_map_t){2, 6}; /* T */
        case 0x16: return (key_map_t){3, 6}; /* U */
        case 0x2F: return (key_map_t){3, 7}; /* V */
        case 0x11: return (key_map_t){1, 1}; /* W */
        case 0x2D: return (key_map_t){2, 7}; /* X */
        case 0x15: return (key_map_t){3, 1}; /* Y */
        case 0x2C: return (key_map_t){1, 4}; /* Z */

        case 0x02: return (key_map_t){7, 0}; /* 1 */
        case 0x03: return (key_map_t){7, 3}; /* 2 */
        case 0x04: return (key_map_t){1, 0}; /* 3 */
        case 0x05: return (key_map_t){1, 3}; /* 4 */
        case 0x06: return (key_map_t){2, 0}; /* 5 */
        case 0x07: return (key_map_t){2, 3}; /* 6 */
        case 0x08: return (key_map_t){3, 0}; /* 7 */
        case 0x09: return (key_map_t){3, 3}; /* 8 */
        case 0x0A: return (key_map_t){4, 0}; /* 9 */
        case 0x0B: return (key_map_t){4, 3}; /* 0 */

        case 0x39: return (key_map_t){7, 4}; /* SPACE */
        case 0x1C: return (key_map_t){0, 1}; /* RETURN */
        case 0x0E: return (key_map_t){0, 0}; /* BACKSPACE -> INST/DEL */
        case 0x33: return (key_map_t){5, 7}; /* , */
        case 0x34: return (key_map_t){5, 4}; /* . */
        case 0x35: return (key_map_t){6, 7}; /* / */
        case 0x27: return (key_map_t){6, 2}; /* ; */
        case 0x0C: return (key_map_t){5, 3}; /* - */
        case 0x0D: return (key_map_t){5, 0}; /* = -> C64 + */
        case 0x1A: return (key_map_t){5, 6}; /* @ */
        case 0x1B: return (key_map_t){6, 1}; /* * */
        case 0x2A: return (key_map_t){1, 7}; /* Left Shift */
        case 0x36: return (key_map_t){6, 4}; /* Right Shift */
        case 0x1D: return (key_map_t){7, 2}; /* Left Ctrl */
        case 0x01: return (key_map_t){7, 7}; /* Esc -> RUN/STOP */

        /* --- rest of the full C64 matrix (keys with no simple ASCII
         * equivalent - see host/kvm_host.c:parse_escape_seq and
         * ascii_to_key for what actually generates these codes) --------- */
        case 0x4D: return (key_map_t){0, 2}; /* CRSR LEFT/RIGHT (shared key) */
        case 0x50: return (key_map_t){0, 7}; /* CRSR UP/DOWN (shared key) */
        case 0x3B: return (key_map_t){0, 4}; /* F1/F2 */
        case 0x3D: return (key_map_t){0, 5}; /* F3/F4 */
        case 0x3F: return (key_map_t){0, 6}; /* F5/F6 */
        case 0x41: return (key_map_t){0, 3}; /* F7/F8 */
        case 0x47: return (key_map_t){6, 3}; /* HOME/CLR */
        case 0x2B: return (key_map_t){6, 0}; /* pound sign (£) */
        case 0x38: return (key_map_t){7, 5}; /* C= (Commodore) */
        case 0x29: return (key_map_t){6, 6}; /* up arrow / pi */
        case 0x56: return (key_map_t){7, 1}; /* left arrow (PETSCII) */
        case 0x0F: return (key_map_t){6, 5}; /* = (dedicated C64 key, distinct from "+") */

        default: return KM_NONE;
    }
}

/* RESTORE on a real C64 is NOT part of the keyboard matrix - it's a
 * separate button wired directly to the CPU's NMI line. The host signals
 * it with an agreed-upon sentinel byte 0xFF (outside the normal "make"/
 * "break" range for actually mapped keys), which poll_keyboard()
 * intercepts BEFORE handing off to scancode_to_c64()/the matrix, turning
 * it into a one-shot NMI request handled in the main loop alongside
 * cia2_nmi_pending() - see host/kvm_host.c (terminal F12). */
static bool g_restore_pending = false;

static void poll_keyboard(void)
{
    /* Deliberately only ONE event per frame (~50 Hz): the host queues the
     * "make" and "break" codes of the same key back-to-back (see
     * kvm_host.c: poll_host_stdin), and if this function drained the
     * whole queue at once, the 6502 would never get to see the "pressed"
     * state in between - the KERNAL's scan routine only polls the matrix
     * once per clock interrupt. Limiting to one event per frame gives
     * ~20 ms of key "hold time", which is plenty for the KERNAL to
     * detect. */
    uint8_t sc = inb(PORT_KEYBOARD);
    if (sc == 0) return;
    if (sc == 0xFF) { g_restore_pending = true; return; }
    bool release = (sc & 0x80) != 0;
    key_map_t km = scancode_to_c64((uint8_t)(sc & 0x7F));
    /* row/col swap: an empirically verified transposition between the
     * scancode_to_c64() table and the row/column convention expected by
     * the KERNAL's scan routine (see the comment in the README/tests). */
    if (km.row != 0xFF) cia_keyboard_set(km.col, km.row, !release);
}

/* --- startup --------------------------------------------------------------- */

static void load_roms(void)
{
    uint32_t n;

    n = rom_kernal_file_len < ROM_KERNAL_SIZE ? rom_kernal_file_len : ROM_KERNAL_SIZE;
    memcpy(rom_kernal, rom_kernal_file, n);

    n = rom_basic_file_len < ROM_BASIC_SIZE ? rom_basic_file_len : ROM_BASIC_SIZE;
    memcpy(rom_basic, rom_basic_file, n);

    n = rom_chargen_file_len < ROM_CHARGEN_SIZE ? rom_chargen_file_len : ROM_CHARGEN_SIZE;
    memcpy(rom_chargen, rom_chargen_file, n);

    n = rom_simons_file_len < ROM_SIMONS_SIZE ? rom_simons_file_len : ROM_SIMONS_SIZE;
    memcpy(rom_simons, rom_simons_file, n);
}

void kernel_main(multiboot_info_min_t *mb_info)
{
    debug_puts("=== C64-on-KVM: unikernel boot ===\n");

    load_roms();

    pla_reset();
    cartridge_reset();
    vic2_reset();
    cia_reset();
    sid_reset();
    reu_reset();

    fake6502_context cpu;
    memset(&cpu, 0, sizeof(cpu));
    fake6502_reset(&cpu);

    debug_puts("PC after reset = $");
    debug_puthex16(cpu.cpu.pc);
    debug_puts("\n");

    uint8_t *vram = (uint8_t *)(uintptr_t)mb_info->framebuffer_addr;

    const double cycles_per_sample = 985248.0 / (double)SID_SAMPLE_RATE;
    double audio_acc = 0.0;

    for (;;) {
        if (cpu.cpu.pc == 0xF4A5) {
            do_fast_load(&cpu);
            continue;
        }
        if (cpu.cpu.pc == 0xF5DD) {
            do_fast_save(&cpu);
            continue;
        }
        if (cpu.cpu.pc == 0xF700) {
            do_sid_load(&cpu);
            continue;
        }
        uint32_t before = (uint32_t)cpu.emu.clockticks;
        fake6502_step(&cpu);
        uint32_t delta = (uint32_t)cpu.emu.clockticks - before;
        if (delta == 0) delta = 2;

        cia_tick((int)delta);
        bool frame_done = vic2_tick((int)delta);

        audio_acc += (double)delta;
        while (audio_acc >= cycles_per_sample) {
            audio_acc -= cycles_per_sample;
            outw(PORT_AUDIO_SAMPLE, (uint16_t)sid_generate_sample());
        }

        if (cia2_nmi_pending() || g_restore_pending) {
            fake6502_nmi(&cpu);
            g_restore_pending = false;
        }
        if (!(cpu.cpu.flags & FAKE6502_INTERRUPT_FLAG) &&
            (cia1_irq_pending() || vic2_irq_pending() || reu_irq_pending())) {
            fake6502_irq(&cpu);
        }

        if (frame_done) {
            poll_keyboard();
            memcpy(vram, vic2_framebuffer, sizeof(vic2_framebuffer));
        }
    }
}
